# Generated by Django 5.1.1 on 2025-05-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_name_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='district_state',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
